project:
  type: website
  output-dir: docs
  
website:
  title: "Class website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Data Viz"
        menu:
            - text: "Gas Price "
              href: plot1.html
            - text: "Pixar Films"
              href: pixarmovies.html
            - text: "BBC artciles"
              href: bbcarticles.html
          

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

